name: second-workflow
on:
  issue_comment:
    types: [created, deleted]
jobs:
  outbut:
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@v3
      - name: print the outbut
        run: echo "${{ toJSON(github.event) }}"